version: '2'
services:
  mysql163:
    image: mysql:5.6.36
    container_name: mysql163
    networks:
      - default
    environment:
      MYSQL_DATABASE: "spider163"
      MYSQL_ROOT_PASSWORD: "a1b2c3d4e"
    volumes:
      - ./_dev/mysql:/var/lib/mysql:z
    ports:
      - "3336:3306"
    expose:
      - "3306"
  spider163:
    image: chengtian/spider163:2.7.5
    container_name: spider163
    volumes:
      - ../:/root/code
    ports:
      # 将容器端口与宿主机绑定, 以便外部访问
      - "1630:1630"
    expose:
      - "1630"
    links:
      - mysql163:mysql163.localhost
    depends_on:
      - mysql163
    networks:
      - default
networks:
  default:
    external:
      name: spider163
